---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-rollouts
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  # - clusters:
  #     selector:
  #       matchLabels:
  #         env: dev
  - list:
      elements:
      - cluster: dev
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: 'argo-rollouts'
    spec:
      project: "default"
      sources:
      - repoURL: https://argoproj.github.io/argo-helm
        targetRevision: 2.40.5
        chart: argo-rollouts
        helm:
          valueFiles:
          - $values/charts/argo-rollouts/values.yaml
      - repoURL: https://github.com/gabrielsrochaa/argocd_app_of_apps.git
        targetRevision: main
        ref: values
      destination:
        server: {{ .url }}
        namespace: argo-rollouts
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true