apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-rollouts
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters:
        selector:
          matchLabels:
            kubernetes.io/instance: "*"
  template:
    metadata:
      name: "argo-rollouts-{{ .name }}"
    spec:
      project: default
      source:
        repoURL: https://argoproj.github.io/argo-helm
        targetRevision: 2.40.5
        chart: argo-rollouts
      destination:
        name: {{ .server }}
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true