apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-rollouts
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters:
      selector:
        matchLabels:
          env: dev
      values:
        clusterName: '{{ .name }}'
  template:
    metadata:
      name: 'argo-rollouts-{{ .values.clusterName }}'
    spec:
      project: "default"
      source:
        repoURL: argoproj.github.io
        targetRevision: 2.40.5
        chart: argo-rollouts
      destination:
        server: '{{ .server }}'
        namespace: argo-rollouts
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true