---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters: {}
  template:
    metadata:
      name: 'argo-rollouts-{{ .name }}'
    spec:
      project: "default"
      sources:
      - repoURL: https://argoproj.github.io/argo-helm
        targetRevision: 2.40.4
        chart: argo-rollouts
        helm:
          valueFiles:
          - $values/charts/argo-rollouts/values.yaml
      - repoURL: https://github.dev/gabrielsrochaa/argocd_app_of_apps.git
        targetRevision: main
        ref: values
      destination:
        server: {{ .server }}
        namespace: argo-rollouts
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true